name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  inject-config:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v2

      - name: Create Firebase Config File
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
        run: |
          echo "const config = {
            firebase: {
              apiKey: '${FIREBASE_API_KEY}',
              authDomain: '${FIREBASE_AUTH_DOMAIN}',
              projectId: '${FIREBASE_PROJECT_ID}',
              storageBucket: '${FIREBASE_STORAGE_BUCKET}',
              messagingSenderId: '${FIREBASE_MESSAGING_SENDER_ID}',
              appId: '${FIREBASE_APP_ID}',
              measurementId: '${FIREBASE_MEASUREMENT_ID}',
            },
          };" >> ./config.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
